name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
  pull_request: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
  visual-regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Build Storybook
        run: pnpm storybook:build
      - name: Run visual regression tests
        id: ld
        uses: pmqueiroz/lumen-diff@v0.2.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: ${{ failure() && steps.ld.conclusion == 'failure' && !github.event.pull_request.draft }}
        with:
          add-paths: .lumendiff/baseline
          base: ${{ github.head_ref }}
          branch: 'chore/visual-regression-update-for-${{ github.event.number }}'
          commit-message: 'chore: update lumendiff baselines for #${{ github.event.number }}'
          delete-branch: true
          title: 'chore: update visual regression baseline for #${{ github.event.number }}'
          token: ${{ github.token }}
